### ISSUE TITLE
useAllDevices already true

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#1]
https://github.com/packet-labs/Rook-on-Bare-Metal-Workshop/blob/master/Lab-C.md

useAllDevices is already set to true but the instructions are to set it to true. Perhaps this is from upgrading to Rook 1.0?

**Comment by johnstudarus** [comment]
Set useAll to false?
Then specifically list the one master node? (and add students add storage node later)

https://github.com/packet-labs/Rook-on-Bare-Metal-Workshop/blob/master/files/cluster.yml#L91-L93

**Comment by Miouge1** [comment]
I think we can keep `useAllNodes: true` and `useAllDevices: true`, once they reach the lab that runs `scale.yml` it will add the second node and it should automatically join the Ceph cluster and format all available block devices on the c2.medium server.

**Comment by Miouge1** [comment]
After running some tests, it looks like `useAllNodes: true` doesn't pick up a new node. Rook finds the  block devices but doesn't assign them to the CephCluster.

Then I suggest to do `useAllNodes: false` and `useAllDevices:  true`. Will make a PR for that.

**Comment by Miouge1** [comment]
I've I've also updated Lab40 to include the add `node2` in the list of nodes.
