### ISSUE TITLE
Switch to m2.xlarge

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#18]
There are way more m2.xlarge's available over the c2.medium. Switch?

**Comment by Miouge1** [comment]
How is the block device layout on m2.xlarge I think you mentioned that they had 1 block device only?

**Comment by johnstudarus** [comment]
m2.xlarge only has a single NVMe device so doesn't make sense to switch. We'll stick to the c2.medium.
