### ISSUE TITLE
sshd not restarting?

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#23]
https://github.com/packet-labs/Rook-on-Bare-Metal-Workshop/blob/master/setup/handlers/main.yml#L3

Should "sshd" be "ssh"?

Built a new lab master and the sshd.config was updated but it appears sshd wasn't restarted so the change didn't take effect.

**Comment by Miouge1** [comment]
Things worked out of the box on the new lab masters, so I think the reload works correctly.
