### ISSUE TITLE
Lab10 - additional storage dirs - bonus track

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#24]
Add an additional "bonus" step to Lab 10 where additional storageDirs are added to add additional OSDs to simulate additional drives.

**Comment by Miouge1** [comment]
Lab 91

**Comment by Stan92** [comment]
Hi @Miouge1, 
I can't find the lab 91, 
Is it possible to use this configuration for the storage
Using the lvmdiskscan  command I get this configuration, and currently I have only the sda1 managed with Rook.. how can I add the sdab? (I've posted a question on Stackoverflow)..
```
/dev/sda1 [< 38.15 Gib]
/dev/sdab [< 200.00 Gib]
1 disk
1 partition
0 LVM physical volume whole disks
0 LVM physical volumes

```
Thanks for your support.

**Comment by johnstudarus** [comment]
The lab steps to grow the cluster are in:
https://github.com/packet-labs/Rook-on-Bare-Metal-Workshop/blob/master/Lab40.md

If you have general Rook support questions, I recommend reaching out to the Rook community via their Forum or Slack. 

https://rook.io/
