### ISSUE TITLE
lab file ownership

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#3]
When the main.yaml playbook is run, the resulting files under the lab directories are all owned by root. These need to be owned by the lab user.

**Comment by johnstudarus** [comment]
This will only be an issue if the lab user needs to run Terraform (which they probably will not). I'm likely going to close out this issue.

**Comment by Miouge1** [comment]
For cluster.tf that's not going to be a problem, but for inventory.ini that will be a problem if we want them to run the Kubespray scale.yml playbook to add an additional node.

I'll fix that.
