### ISSUE TITLE
inconsistent node names

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#30]
lab30@studarus-lab:/$ ssh node1 hostname
node1
lab30@studarus-lab:/$ ssh node2 hostname
lab30-k8s-node-1

Somehow the terraform needs to be modified to get meaningful hostnames.

**Comment by Miouge1** [comment]
The hostname in node2 will be changed by ansible in Lab40. So once you run `scale.yml` it should be consistent.
