### ISSUE TITLE
node2 CephCluster syntax

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#36]
In Lab40:
https://github.com/packet-labs/Rook-on-Bare-Metal-Workshop/blob/master/Lab40.md

Is the dashboard in front of node2 needed or should it not be there?

Should:
```
- name: node2
```
be
```
  name: node2
```

**Comment by Miouge1** [comment]
Yes there should be a `-`, let me add an example in Lab40 to make things clearer.
