### ISSUE TITLE
rgw secrets - Lab 60

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#37]
Docs are currently looking for the following secret:
rook-ceph-object-user-my-store-my-user 

But the following is available:
rook-ceph-rgw-my-store-keyring

**Comment by Miouge1** [comment]
`keyring` secret is something else. Can you double check that the `object-user.yaml` got applied correctly?

**Comment by Miouge1** [comment]
I tested it again today, the secrets showed up.
