### ISSUE TITLE
multi-node URL

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#38]
When there are two nodes, the "get nodes" command might not return the correct nodes.

IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[].address}')

This might be impacting Lab 80 getting the URL.

**Comment by Miouge1** [comment]
This should be fine since we are using NodePort services. It means that all the Kube nodes of the clusters are able to serve that service.

**Comment by johnstudarus** [comment]
OK - I'll retest Lab 80 and see if there is a different issue...
