### ISSUE TITLE
enable password logins

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#5]
By default, logins are not allowed via passwords.  They need to be enabled using:

cat <<EOF >> /etc/ssh/sshd_config
Match user lab*
  PasswordAuthentication yes
EOF
service sshd restart

**Comment by johnstudarus** [comment]
@Miouge1 do you want to put this into the playbooks?

**Comment by johnstudarus** [comment]
Added to the README

**Comment by Miouge1** [comment]
Yes, I'll add that as a check in playbook.

**Comment by Miouge1** [comment]
I've added that in the playbook with dfdde8ef57a1695809e1163d1db58d8d68f883da do we still want to keep a mention of it in the README?
