### ISSUE TITLE
ceph osd crush tunables hammer still needed?

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#61]
Is this no longer needed since KubeSpray is deploying Ubuntu 16.04? @JohnHaan 

https://github.com/packet-labs/Rook-on-Bare-Metal-Workshop/blame/master/Lab20.md#L8-L16

**Comment by JohnHaan** [comment]
I guess so, but it needs to test to make sure.
I will test on it and if not needed I would remove from the guide.^^


2019년 10월 15일 (화) 오전 7:39, johnstudarus <notifications@github.com>님이 작성:

**Comment by Miouge1** [comment]
The workshop always ran on 16.04, so that comment should probably say "Ubuntu 16.04" instead of "Ubuntu 14.04".

Last workshop I did (2 weeks ago) the tunables were still necessary, but I didn't dig too deep into it.

**Comment by johnstudarus** [comment]
ok - I've updated the docs to reflect the correct Ubuntu version.
