### ISSUE TITLE
Ansible version update

### ISSUE THREAD

**Issue by vielmetti** [packet-labs/Rook-on-Bare-Metal#69]
Per PR #68 please review a change suggested to bring Ansible to a newer point release, as a consequence of an automated review.

I'll defer to @johnstudarus to help assess whether this change is fully compatible or if it's going to trigger a cascade of other changes.

**Comment by displague** [comment]
The version of Ansible has been updated on the recommendation of a high-security dependabot generated PR.  Let's open new issues if needed to address any breakages. (cc @johnstudarus)
