### ISSUE TITLE
tag storage node and add to Rook later

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/Rook-on-Bare-Metal#8]
Cluster.yml adds in the storage node right away. Can it be added later via a tag?

Use the master at first (via RookDir FS) and then later lab add storage. Students add a tag "storage" to the node and then Rook adds it? (new Lab # needed)

**Comment by Miouge1** [comment]
I think this should addressed by #12 
The idea is to uncomment the second node from the inventory, run `scale.yml` then the node shows up in Kubernetes.
